project_id = "stoa"

[auth]
site_url = "https://stoa-coaching.fr"
additional_redirect_urls = ["https://stoa-coaching.fr/academie.html", "https://www.stoa-coaching.fr/academie.html", "http://127.0.0.1:4173/academie.html"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true

[auth.external.discord]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_DISCORD_SECRET)"
